from microbit import *
import music
import superbit
import microbit
import neopixel

display.show(Image.HAPPY)
np = neopixel.NeoPixel(pin12, 4)


while True:
    music.play('E4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('E4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('F4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('G4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('G4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('F4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('E4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('D4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('C4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('C4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('D4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('E4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('E4:6')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('D4:2')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('D4:2')
    superbit.motor_control(superbit.M1, 255, 0)
    microbit.sleep(500)
    music.play('E4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('E4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('F4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('G4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('G4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('F4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('E4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('D4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('C4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('C4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('D4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('E4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('D4:6')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('C4:2')
    superbit.motor_control(superbit.M1, 255, 0)
    music.play('C4:2')
    superbit.motor_control(superbit.M1, 255, 0)
    microbit.sleep(1000)



